# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name Debug_Assert
#' @title Debug_Assert
#' @description Illustration of \sQuote{Debug_Assert}
#' @return All functions have a default return of \code{TRUE}
NULL

#' @rdname Debug_Assert
module_a_func0 <- function() {
    .Call(`_RcppDA_module_a_func0`)
}

#' @rdname Debug_Assert
module_a_func1 <- function() {
    .Call(`_RcppDA_module_a_func1`)
}

#' @rdname Debug_Assert
module_a_func1b <- function() {
    .Call(`_RcppDA_module_a_func1b`)
}

#' @rdname Debug_Assert
module_a_func2 <- function() {
    .Call(`_RcppDA_module_a_func2`)
}

#' @rdname Debug_Assert
module_a_func3 <- function() {
    .Call(`_RcppDA_module_a_func3`)
}

#' @rdname Debug_Assert
module_a_func4 <- function() {
    .Call(`_RcppDA_module_a_func4`)
}

